server:
  port: 8002
  
spring:
  application:
    name: member-service
  profiles:
    active:
    - mariadb
    - service
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-member.sql
  redis:
    host: redis
    port: 6379
  config:
    import: optional:configserver:http://docker-config-service:8888

springdoc:
  title: Member API Documents
  version: 1.0.0
  swagger-ui:
    path: /api-docs
  packages-to-scan: edu.jong.board.member
