server:
  port: 8002
  
spring:
  redis:
    host: redis
    port: 6379
  application:
    name: member-service
  profiles:
    active:
    - mariadb
    - service
  config:
    import: optional:configserver:http://config-service:8888

springdoc:
  swagger-ui:
    title: Member API Documents
    version: 1.0.0
    path: /api-docs
  packages-to-scan: edu.jong.board.member
