version: "3"

services:
  role-service:
    image: openjdk:8
    hostname: member-service
    container_name: member-service
    environment:
      - TZ=Asia/Seoul
    ports:
      - 8002:8002
    volumes:
      - ./src/main/resources:/app/resources
      - ./target/spring-board-member-service-0.0.1-SNAPSHOT.jar:/app/application.jar
    command: java -jar -Dspring.config.location=/app/resources/application-deploy.yml /app/application.jar
    networks:
      - default
      - mariadb
      - redis
      - config
      - discovery

networks:
  default:
    name: board_net
    external: true
  mariadb:
    name: mariadb_net
    external: true
  redis:
    name: redis_net
    external: true
  config:
    name: config_net
    external: true
  discovery:
    name: discovery_net
    external: true
    