server:
  port: 8001
  
spring:
  application:
    name: role-service
  profiles:
    active:
    - mariadb
    - service
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-role.sql
  redis:
    host: 127.0.0.1
    port: 6379
  config:
    import: optional:configserver:http://127.0.0.1:8888

springdoc:
  swagger-ui:
    title: Role API Documents
    version: 1.0.0
    path: /api-docs
  packages-to-scan: edu.jong.board.role
